import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from 'react';

export default function Home() {

    const [count, setCount] = useState(0)
    const [todoList, setTodoList] = useState(["toto", "tata"])
    const [task, setTask] = useState("")

    const addTask = event => {
        setTodoList(prevArray => [...prevArray, task])
    }
    const handleOnChange = event => {
        const value = event.target.value;
        setTask(value);
    };

    const deleteTask = index => {
        setTodoList(todoList.filter((_, i) =>
            index !== i
        ))
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Hello</h1>
                <h3>{ count }</h3>
                <button onClick={() => setCount(prev => prev + 1)}>Click</button>

                <input type="text" onChange={handleOnChange}/>
                <button onClick={() => addTask()}>Add</button>

                {todoList.length > 0 && (
                    todoList.map((todo, i) => {
                        return(
                            <div key={i}>
                                <input type="text" disabled value={todo}></input>
                                <button onClick={() => deleteTask(i)}>Delete</button>
                            </div>

                        )
                    })
                )}


            </main>


        </div>
    )
}