import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState} from "react";

export default function Home() {
    let [count, setCount] = useState(0)
    let [todoList, setTodoList] = useState(["toto", "titi", "tata"])
    let [addTask, setAddTask] = useState("")

    const Task = event =>{
        setTodoList(prevArray =>[...prevArray, addTask])
    }

    const handleChange = event => {
        const value = event.target.value;
        setAddTask(value)
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1>Hello</h1>
                <h3>Count : {count}</h3>
                <button onClick={() => setCount(prev => count++)}>Clique</button>
                <input type="text" onChange={handleChange}/>
                <input type="submit" onClick={()=> Task()} value="Submit"/>
                {todoList.length > 0 && (
                    todoList.map((todo, i) => {
                        return (
                            <p key={i}>{todo}</p>
                        )
                    })
                )}
            </main>
        </div>
    )
}
